apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-nestjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-nestjs
  template:
    metadata:
      labels:
        app: graphql-nestjs
    spec:
      containers:
        - name: graphql-nestjs
          image: vigneshk1045/graphql-nestjs:2e3120ff
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: graphql-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: graphql-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: graphql-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: graphql-config
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: graphql-config
                  key: DB_NAME
