apiVersion: v1
kind: Service
metadata:
  name: graphql-nestjs-service
spec:
  type: NodePort
  selector:
    app: graphql-nestjs
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30090
